Repository beresdev/ecommerce-v02, pull requests merged in 2023-05, with the labels that each got.

#14 2 setup tailwind+assets
  package.json
  src/App.css
  src/index.css
  tailwind-default.config.js
  tailwind.config.js
Labels: Styles

#15 Implementación de router
  src/App.jsx
  src/utils/routes.jsx
Labels: enhancement

#16 Maquetado de componente layout
  src/App.jsx
  src/components/Layout/Layout.jsx
Labels: enhancement

#19 Estilos de layout
  src/App.css
  src/App.jsx
  src/components/Layout/Layout.css
  src/components/Layout/Layout.jsx
Labels: Styles

#25 Correccion de estilos a product card
  product-styles.css
  src/App.css
  src/components/ProductCard/ProductCard.css
  src/components/ProductCard/ProductCard.jsx
  src/main.jsx
Labels: bug, Styles

#27 11 cart implementación implementation
  src/App.jsx
  src/components/Cart/CartItems.css
  src/components/Cart/CartItems.jsx
  src/components/Layout/Layout.jsx
  src/components/ProductCard/ProductCard.jsx
Labels: enhancement
